site_name: mkdocstrings
site_description: Automatic documentation from docstrings, for mkdocs.
site_url: https://mkdocstrings.github.io/
repo_url: https://github.com/pawamoy/mkdocstrings
repo_name: pawamoy/mkdocstrings

nav:
  - Overview: "index.md"
  - Reference:
    - handlers:
      - Base: "reference/handlers/__init__.md"
      - python.py: "reference/handlers/python.md"
    - extension.py: "reference/extension.md"
    - plugin.py: "reference/plugin.md"
    - utils.py: "reference/utils.md"
  - Contributing: "contributing.md"
  - Code of Conduct: "code_of_conduct.md"
  - Changelog: "changelog.md"
  - Credits: "credits.md"

theme:
  name: "material"

extra_css:
  - custom.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/mkdocstrings
