site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://mkdocstrings.github.io/"
repo_url: "https://github.com/mkdocstrings/mkdocstrings"
edit_uri: "blob/master/docs/"
repo_name: "mkdocstrings/mkdocstrings"

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra_css:
- css/style.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_credits.py
    - docs/gen_doc_stubs.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("docs")
        selection:
          new_path_syntax: yes
        import:  # demonstration purpose in the docs
        - https://docs.python-requests.org/en/master/objects.inv
    watch:
    - src/mkdocstrings
