[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mkdocstrings"
version = "0.15.2"
description = "Automatic documentation from sources, for MkDocs."
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
license = "ISC License"
readme = "README.md"
repository = "https://github.com/mkdocstrings/mkdocstrings"
homepage = "https://github.com/mkdocstrings/mkdocstrings"
keywords = ["mkdocs", "mkdocs-plugin", "docstrings", "autodoc", "documentation"]
packages = [ { include = "mkdocstrings", from = "src" } ]

[tool.poetry.dependencies]
python = "^3.6.2"
Jinja2 = ">=2.11.1, <4.0"
Markdown = "^3.3"
MarkupSafe = ">=1.1, <3.0"
mkdocs = "^1.1.1"
mkdocs-autorefs = ">=0.1, <0.4"
pymdown-extensions = ">=6.3, <9.0"
pytkdocs = ">=0.2.0, <0.13.0"

[tool.poetry.dev-dependencies]
# formatting, quality, tests
autoflake = "^1.4"
black = "^21.9b0"
isort = "^5.9.3"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-randomly = "^3.10.1"
pytest-sugar = "^0.9.4"
pytest-xdist = "^2.3.0"

# tasks
duty = "^0.7.0"
git-changelog = "^0.4.2"
toml = "^0.10.2"

# flake8 plugins
darglint = "^1.8.0"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.3"
flake8-bugbear = "^21.9.1"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.6.1"
flake8-docstrings = "^1.6.0"
flake8-pytest-style = "^1.5.0"
flake8-string-format = "^0.3.0"
flake8-tidy-imports = "^4.4.1"
flake8-variables-names = "^0.0.4"
pep8-naming = "^0.12.1"

# docs
mkdocs-coverage = "^0.2.4"
mkdocs-material = "^7.2.8"
mkdocs-gen-files = {version = "^0.3.3", markers = "python_version>='3.7'"}
mkdocs-section-index = "^0.3.1"
mkdocs-literate-nav = "^0.4.0"

[tool.poetry.plugins."mkdocs.plugins"]
mkdocstrings = "mkdocstrings.plugin:MkdocstringsPlugin"

[tool.black]
line-length = 120
exclude = "tests/fixtures"

[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "mkdocstrings"
include_trailing_comma = true
